name: Lint and Style Check




on:
pull_request:
branches: [ main, master ]
push:
branches: [ main, master ]




jobs:
lint:
name: Code Style and Quality Check
runs-on: ubuntu-latest

steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Set up Python
    uses: actions/setup-python@v5
    with:
      python-version: "3.10"

  - name: Install linters
    run: |
      pip install black flake8 isort nbqa

  - name: Check code formatting with Black
    run: black --check .

  - name: Check import order with isort
    run: isort --check-only .

  - name: Lint Python scripts with Flake8
    run: flake8 .

  - name: Lint Jupyter Notebooks with nbQA
    run: |
      nbqa black --check notebooks/
      nbqa flake8 notebooks/